default: &default
  adapter: postgresql
  encoding: utf8
  database: byte_slash
  pool: 5

development:
  <<: *default
  database: byte_slash

production:
  <<: *default
  adapter: postgresql
  database: <%= ENV["DATABASE_NAME"] %>
  url: <%= ENV["DATABASE_URL"] %>